version: '3'
services:
  sismor-base:
    build: .
    volumes:
      - ./:/src/sismor-base
    working_dir: /src/sismor-base
    ports:
      - "8080:8080"

  # redis:
  #       image: redis:alpine
  #       container_name: redis
  #       restart: unless-stopped
  #       ports:
  #           - "6379:6379"

  mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./storage/mysql:/var/lib/mysql


networks:
  default:
    name: app-network