version: '3'
services:
  sismor-base:
    build: .
    volumes:
      - ./:/src/sismor-base
    working_dir: /src/sismor-base
    ports:
      - "8080:8080"
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
networks:
  app-network:
    driver: bridge