//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Users struct {
	ID       int32
	Name     string
	Password string
	Email    string
}

func (user *Users)GetID() int32 {
	return user.ID
}
